@extends('layout')
@section('content')
<div class="app-shell" data-role="{{ auth()->user()->role }}" data-actor="{{ auth()->user()->name }}" data-actor-key="user:{{ auth()->id() }}">
<aside class="sidebar"><a class="school-brand" href="/"><img src="/assets/document-mark.svg" alt="Document management icon"><span>DMS<span class="brand-sub">DOCUMENT MANAGEMENT</span></span></a>
<div class="nav-caption">WORKSPACE</div><nav aria-label="Main navigation">
<button class="nav-item active" data-view="overview"><span aria-hidden="true">▦</span> Home</button>
<button class="nav-item" data-view="documents"><span aria-hidden="true">▤</span> All documents</button>
<button class="nav-item" data-view="files">▤ My files</button>
<button class="nav-item" data-view="recent">◷ Recent</button>
<button class="nav-item" data-view="starred">☆ Starred</button>
<button class="nav-item" data-view="trash">♲ Trash</button>
<button class="nav-item" data-view="history"><span aria-hidden="true">◷</span> Central history</button>
<div class="nav-caption">ADMINISTRATION</div><button class="nav-item" data-view="integrations"><span aria-hidden="true">⇄</span> Integrations</button>
@if(auth()->user()->role==='admin')<button class="nav-item" data-view="audit"><span aria-hidden="true">◷</span> Audit trail</button>@endif
<button class="nav-item" data-view="guide"><span aria-hidden="true">ⓘ</span> Workspace guide</button></nav>
<div class="sidebar-bottom"><div class="school-pill">Main campus</div><p>One school.<br>Connected records.</p><span class="school-year">Academic year 2026–2027</span></div></aside>
<div class="main-shell"><header class="topbar"><button id="menu-toggle" class="btn mobile-menu" aria-label="Toggle navigation">☰</button><span class="breadcrumb-label">School workspace <span>/</span> <strong id="breadcrumb">Overview</strong></span><div class="user-box"><span class="avatar">{{ substr(auth()->user()->name,0,1) }}</span><div><strong>{{ auth()->user()->name }}</strong><span>{{ ucfirst(auth()->user()->role) }}</span></div><form action="/logout" method="post">@csrf<button class="logout" title="Sign out" aria-label="Sign out">↪</button></form></div></header>
<div class="local-banner"><span>LOCAL DEMONSTRATION</span> Synthetic records · School identity and live ERP connections are not configured.</div>
<main id="main"><div class="page-heading"><div><p class="eyebrow green">RECORDS WORKSPACE</p><h1 id="page-title">Document overview</h1><p id="page-description">A clear view of your school's documents and file activity.</p></div><button id="upload-open" class="btn btn-green"><span aria-hidden="true">＋</span> Upload document</button></div>
<div id="notice" class="alert" role="status" hidden></div>
<section id="repository-panel" class="panel"><div class="panel-heading"><div><h2 id="list-title">Recent documents</h2><span id="list-subtitle" class="muted-label">Only records you are permitted to access</span></div><button id="show-all" class="btn btn-quiet">View all documents</button></div><div class="filter-bar"><div class="search-wrap"><span aria-hidden="true">⌕</span><input class="form-control" id="search" placeholder="Search title, person or reference…" aria-label="Search documents"></div><select id="source-filter" class="form-select" aria-label="Filter source"><option value="">All systems</option>@foreach(config('dms.systems') as $s)<option>{{ $s }}</option>@endforeach</select><select id="status-filter" class="form-select" aria-label="Filter status"><option value="">All statuses</option><option>Available</option><option>Awaiting scan</option></select><button id="reset-filters" class="btn btn-quiet">Reset</button></div>
<div class="table-responsive"><table class="table document-table"><thead><tr><th>Document</th><th>Linked record</th><th>Source system</th><th>Status</th><th>Updated</th><th><span class="visually-hidden">Actions</span></th></tr></thead><tbody id="documents-body"><tr><td colspan="6" class="empty-state">Loading documents…</td></tr></tbody></table></div><div class="table-footer"><span id="result-count">—</span><div><button id="prev-page" class="btn btn-quiet" disabled>Previous</button><span id="page-number">1</span><button id="next-page" class="btn btn-quiet" disabled>Next</button></div></div></section>
<section id="integrations-panel" hidden><div class="integration-intro panel"><h2>Four systems. One document foundation.</h2><p>Each connector gets its own school, campus and source scope. Live connections require the corresponding system's API and credentials.</p></div><div class="integration-grid">@foreach(config('dms.systems') as $i=>$s)<article class="panel connector-card"><span class="connector-number">0{{ $i+1 }}</span><span class="status-badge neutral">Not connected</span><h2>{{ $s }}</h2><p>{{ ['Employee contracts and qualifications.','Application evidence and verification outcomes.','Enrollment requirements and admission evidence.','Restricted payslips and payroll evidence.'][$i] }}</p><div class="connector-footer">Interface available <code>/api/v1</code></div></article>@endforeach</div><section class="panel mt-4"><div class="panel-heading"><h2>Integration event feed</h2><button class="btn btn-quiet" id="refresh-events">Refresh</button></div><p class="panel-copy">Events are saved with document changes. This baseline provides a cursor-based pull feed; live delivery and reconciliation are planned in the backlog.</p><div id="event-list" class="event-list"></div></section></section>
<section id="audit-panel" class="panel" hidden><div class="panel-heading"><h2>Recent record activity</h2><button class="btn btn-quiet" id="refresh-audit">Refresh</button></div><div class="table-responsive"><table class="table"><thead><tr><th>Action</th><th>Actor</th><th>Details</th><th>Time</th></tr></thead><tbody id="audit-body"></tbody></table></div><p class="panel-copy">Latest 250 entries in your school and campus. History cannot be edited through this application.</p></section>
<section id="guide-panel" class="panel guide-panel" hidden><div class="panel-heading"><h2>Using your records workspace</h2></div><div id="guide-accordion"><h3>Upload and security checks</h3><div><p>Choose a category, source system and business reference, then upload a PDF, PNG, JPG or TXT file up to 10 MB. Files stay blocked until a configured malware scanner clears them. Without a scanner, they remain awaiting scan.</p></div><h3>Version history</h3><div><p>Clean files are available without DMS approval. Each replacement preserves previous versions and starts its own security check. Business decisions belong to your users or originating systems.</p></div><h3>Access across school systems</h3><div><p>Registrars see admission and enrollment records. HR sees employee documents. Payroll sees payroll evidence. Administrators see all four sources within their assigned school and campus. Live identity and ERP connections still need configuration.</p></div><h3>Baseline and next delivery phases</h3><div><p>The repository includes the complete 45-story build plan. This first slice implements authentication, scoped document intake, version history, metadata search, audit and an integration feed. Requirement rules, confirmed identity mapping, retention, migration and production operations remain tracked work.</p></div></div></section>
<section id="history-panel" class="panel" hidden>
<div class="panel-heading"><h2>Received business history</h2><button id="history-refresh" class="btn btn-quiet">Refresh</button></div>
<p class="panel-copy">Source records are preserved in receipt order. Older revisions remain in history without replacing a newer snapshot. No live systems are connected yet.</p>
<form id="history-filters" class="filter-bar"><select id="history-source" class="form-select" aria-label="History source"><option value="">All permitted systems</option>@foreach(app(\App\Services\DocumentService::class)->sources(auth()->user()) as $s)<option>{{ $s }}</option>@endforeach</select><input id="history-record" class="form-control" placeholder="Exact record ID" aria-label="Exact history record ID" maxlength="200"><button class="btn btn-green" type="submit">Apply filters</button><button class="btn btn-quiet" type="reset">Reset</button></form>
<div class="table-responsive"><table class="table"><thead><tr><th>Record</th><th>Source</th><th>Revision</th><th>Result</th><th>Received</th><th>Details</th></tr></thead><tbody id="history-body"></tbody></table></div>
<div class="table-footer"><span id="history-count" role="status">No history loaded</span><button id="history-more" class="btn btn-quiet" disabled>Load more</button></div>
</section>
<section id="drive-panel" class="panel" hidden>
<div class="panel-heading"><nav id="drive-crumbs" aria-label="Folder path"></nav><div><button id="drive-new-folder" class="btn btn-green">New folder</button> <button id="drive-layout" class="btn btn-quiet" aria-pressed="false">List view</button></div></div>
<form id="drive-filter" class="filter-bar"><input id="drive-search" class="form-control" maxlength="200" placeholder="Search files by name" aria-label="Search files by name"><select id="drive-sort" class="form-select" aria-label="Sort files"><option value="updated">Last modified</option><option value="name">Name</option></select><button class="btn btn-quiet">Search</button></form>
<div id="drive-drop" tabindex="0" aria-label="Drop files here or use Upload document"><p>Drop files here to upload · Files stay private until security checks pass</p><div id="drive-items" class="drive-grid"></div></div>
<div class="table-footer"><span id="drive-count" role="status"></span><div><button id="drive-prev" class="btn btn-quiet">Previous</button><button id="drive-next" class="btn btn-quiet">Next</button></div></div>
</section>
<footer class="workspace-footer"><span>School Documents</span><span>Document Management System · Baseline v0.1</span></footer></main></div></div>
<div id="upload-dialog" title="Upload document" hidden><form id="upload-form"><div id="upload-tabs"><ul><li><a href="#upload-record">Record details</a></li><li><a href="#upload-file">File & validity</a></li></ul><div id="upload-record"><div class="row g-3"><div class="col-12"><label for="title" class="form-label">Document title</label><input id="title" name="title" class="form-control" required maxlength="200"></div><div class="col-md-6"><label for="subject" class="form-label">Person / record owner</label><input id="subject" name="subject" class="form-control" required maxlength="200"></div><div class="col-md-6"><label for="reference" class="form-label">Business reference</label><input id="reference" name="reference" class="form-control" placeholder="APP-2026-0142" required maxlength="200"></div><div class="col-md-6"><label for="source" class="form-label">Source system</label><select id="source" name="source" class="form-select">@foreach(app(\App\Services\DocumentService::class)->sources(auth()->user()) as $s)<option>{{ $s }}</option>@endforeach</select></div><div class="col-md-6"><label for="category" class="form-label">Document category</label><select id="category" name="category" class="form-select">@foreach(config('dms.categories') as $s)<option>{{ $s }}</option>@endforeach</select></div><div class="col-12"><label for="classification" class="form-label">Classification</label><select id="classification" name="classification" class="form-select"><option>Confidential</option><option>Restricted</option><option>Internal</option></select></div></div></div><div id="upload-file"><label class="form-label" for="file">Select file</label><input type="file" id="file" name="file" class="form-control" accept=".pdf,.png,.jpg,.jpeg,.txt" required><p class="text-secondary small mt-2">PDF, PNG, JPG or TXT · Maximum 10 MB</p><label for="expires_at" class="form-label mt-3">Expiry date (optional)</label><input id="expires_at" name="expires_at" class="form-control" placeholder="YYYY-MM-DD" autocomplete="off"><div class="alert alert-warning mt-4">Security checks must pass before this file can be used.</div></div></div><div id="upload-error" class="alert alert-danger mt-3" role="alert" hidden></div><div class="dialog-actions"><button type="button" id="upload-cancel" class="btn btn-quiet">Cancel</button><button type="submit" id="upload-submit" class="btn btn-green">Upload document</button></div></form></div>
<div id="detail-dialog" title="Document details" hidden><div id="detail-content"></div></div>
<div id="history-dialog" title="Business record history" hidden><div id="history-detail"></div></div>
<div id="drive-dialog" title="File action" hidden><form id="drive-action-form"><div id="drive-action-fields"></div><div class="dialog-actions"><button class="btn btn-green">Save</button></div><p id="drive-action-error" class="text-danger" role="alert"></p></form></div>
<div id="preview-dialog" title="File preview" hidden><pre id="preview-text" class="history-payload" hidden></pre><img id="preview-image" alt="Private document preview" style="max-width:100%;max-height:55vh" hidden><iframe id="file-preview" title="Private file preview" sandbox style="width:100%;height:55vh;border:0" hidden></iframe><p id="preview-note" role="status"></p></div>
@endsection
@section('scripts')<script src="/assets/app.js"></script><script src="/assets/drive.js"></script><script src="/assets/dialog-scroll.js"></script>@endsection
