@extends('layout')
@section('title', 'Document workspace')
@section('content')
@php($personal = in_array(auth()->user()->role, ['student','teacher','employee']))
<div class="app-shell" data-role="{{ auth()->user()->role }}" data-actor="{{ auth()->user()->name }}" data-actor-key="user:{{ auth()->id() }}">
<aside class="sidebar"><a class="school-brand" href="/"><img src="/assets/document-mark.svg" alt="Document management icon"><span>DMS<span class="brand-sub">DOCUMENT MANAGEMENT</span></span></a>
<details id="new-menu" class="new-menu"><summary><span aria-hidden="true">＋</span> New</summary><div class="new-menu-options"><button type="button" id="drive-new-folder"><span aria-hidden="true">▰</span> New folder</button><button type="button" id="upload-open"><span aria-hidden="true">↥</span> File upload</button><button type="button" id="folder-upload-open"><span aria-hidden="true">▰</span> Folder upload</button></div></details><input id="folder-upload-picker" type="file" webkitdirectory multiple hidden><div class="nav-caption">WORKSPACE</div><nav aria-label="Main navigation">
<button class="nav-item active" data-view="overview"><span aria-hidden="true">▦</span> Home</button>
@if(auth()->user()->role==='admin')<button class="nav-item" data-view="documents"><span aria-hidden="true">▤</span> School repository</button>@endif
<div class="files-navigation"><button class="nav-item" data-view="files">▤ My files</button><button id="folders-toggle" class="folders-toggle" aria-label="Expand My files folders" aria-expanded="false" aria-controls="sidebar-folders" hidden>⌄</button></div><div id="sidebar-folders" class="sidebar-folders" hidden></div><button class="nav-item" data-view="shared">♧ Shared with me</button>
<button class="nav-item" data-view="recent">◷ Recent</button>
<button class="nav-item" data-view="starred">☆ Starred</button>
<button class="nav-item" data-view="trash">♲ Trash</button>
@if(!in_array(auth()->user()->role, ['student','teacher','employee']))
<button class="nav-item" data-view="history"><span aria-hidden="true">◷</span> Central history</button>
<div class="nav-caption">ADMINISTRATION</div><button class="nav-item" data-view="integrations"><span aria-hidden="true">⇄</span> Integrations</button>
@endif
@if(auth()->user()->role==='admin')<button class="nav-item" data-view="audit"><span aria-hidden="true">◷</span> Audit trail</button><a class="nav-item" href="/accounts">Accounts & roles</a>@endif
</nav>
</aside>
<div class="main-shell"><header class="topbar"><button id="menu-toggle" class="btn mobile-menu" aria-label="Toggle navigation">☰</button><span class="breadcrumb-label">{{ $personal ? 'My workspace' : 'School workspace' }} <span>/</span> <strong id="breadcrumb">Overview</strong></span><div class="user-box"><span class="avatar">{{ substr(auth()->user()->name,0,1) }}</span><div><strong>{{ auth()->user()->name }}</strong><span>{{ config('dms.role_labels')[auth()->user()->role] ?? 'Workspace user' }}</span></div><form action="/logout" method="post">@csrf<button class="logout" title="Sign out" aria-label="Sign out">↪</button></form></div></header>
<main id="main" tabindex="-1"><span id="main-content" tabindex="-1"></span><div class="page-heading"><div><p class="eyebrow green">{{ $personal ? 'YOUR PERSONAL SPACE' : 'RECORDS MANAGEMENT' }}</p><div class="page-title-row"><h1 id="page-title">Document overview</h1><span class="workspace-help"><button type="button" class="help-trigger" aria-label="Help for this page" aria-describedby="page-help">?</button><span class="help-tooltip" id="page-help" role="tooltip">Organize your documents in one place.</span></span></div><p id="page-description">A clear view of your school's documents and file activity.</p></div></div>
<section id="workspace-welcome" class="workspace-welcome"><div><span class="welcome-kicker">A place for every document</span><h2>{{ $personal ? 'Your files. Your space.' : 'Organized records, connected people.' }}</h2><p>{{ $personal ? 'Keep your documents together, organize them into folders, and find them when you need them.' : 'Manage school documents and account access from one workspace. Connect other systems when you need them.' }}</p></div><div class="welcome-count"><strong id="stat-total">—</strong><span>{{ $personal ? 'your documents' : 'accessible documents' }}</span></div></section>
<div id="notice" class="alert" role="status" hidden></div>
@if(auth()->user()->role==='admin')
<section id="repository-panel" class="panel"><div class="panel-heading"><div><h2 id="list-title">Recent documents</h2><span id="list-subtitle" class="muted-label">Only records you are permitted to access</span></div><button id="show-all" class="btn btn-quiet">View all documents</button></div><div class="filter-bar"><div class="search-wrap"><span aria-hidden="true">⌕</span><input class="form-control" id="search" placeholder="Search title, person or reference…" aria-label="Search documents"></div><select id="source-filter" class="form-select" aria-label="Filter source"><option value="">All systems</option>@foreach(config('dms.systems') as $s)<option>{{ $s }}</option>@endforeach</select><button id="reset-filters" class="btn btn-quiet">Reset</button></div>
<div class="table-responsive"><table class="table document-table"><thead><tr><th>Document</th><th>Linked record</th><th>Source system</th><th>Updated</th><th><span class="visually-hidden">Actions</span></th></tr></thead><tbody id="documents-body"><tr><td colspan="5" class="empty-state">Loading documents…</td></tr></tbody></table></div><div class="table-footer"><span id="result-count">—</span><div><button id="prev-page" class="btn btn-quiet" disabled>Previous</button><span id="page-number">1</span><button id="next-page" class="btn btn-quiet" disabled>Next</button></div></div></section>
@endif
<section id="integrations-panel" hidden><div class="integration-intro panel"><h2>Optional school system connections</h2><p>Your document workspace works independently. Connect admission, enrollment, employee or payroll systems when your school is ready.</p></div><div class="integration-grid">@foreach(config('dms.systems') as $i=>$s)<article class="panel connector-card"><span class="connector-number">0{{ $i+1 }}</span><h2>{{ $s }}</h2><p>{{ ['Employee contracts and qualifications.','Application evidence and verification outcomes.','Enrollment requirements and admission evidence.','Restricted payslips and payroll evidence.'][$i] }}</p><div class="connector-footer">Setup required</div></article>@endforeach</div><section class="panel mt-4"><div class="panel-heading"><h2>Integration event feed</h2><button class="btn btn-quiet" id="refresh-events">Refresh</button></div><p class="panel-copy">Document changes are recorded here for connected systems. Integration setup is managed by your school administrator.</p><div id="event-list" class="event-list"></div></section></section>
<section id="audit-panel" class="panel" hidden><div class="panel-heading"><h2>Recent record activity</h2><button class="btn btn-quiet" id="refresh-audit">Refresh</button></div><div class="table-responsive"><table class="table"><thead><tr><th>Action</th><th>Actor</th><th>Details</th><th>Time</th></tr></thead><tbody id="audit-body"></tbody></table></div><p class="panel-copy">Latest 250 entries in your school and campus. History cannot be edited through this application.</p></section>
<section id="history-panel" class="panel" hidden>
<div class="panel-heading"><h2>Received business history</h2><button id="history-refresh" class="btn btn-quiet">Refresh</button></div>
<p class="panel-copy">Source records are preserved in receipt order. Older revisions remain in history without replacing a newer snapshot. No live systems are connected yet.</p>
<form id="history-filters" class="filter-bar"><select id="history-source" class="form-select" aria-label="History source"><option value="">All permitted systems</option>@foreach(app(\App\Services\DocumentService::class)->sources(auth()->user()) as $s)<option>{{ $s }}</option>@endforeach</select><input id="history-record" class="form-control" placeholder="Exact record ID" aria-label="Exact history record ID" maxlength="200"><button class="btn btn-green" type="submit">Apply filters</button><button class="btn btn-quiet" type="reset">Reset</button></form>
<div class="table-responsive"><table class="table"><thead><tr><th>Record</th><th>Source</th><th>Revision</th><th>Result</th><th>Received</th><th>Details</th></tr></thead><tbody id="history-body"></tbody></table></div>
<div class="table-footer"><span id="history-count" role="status">No history loaded</span><button id="history-more" class="btn btn-quiet" disabled>Load more</button></div>
</section>
<section id="drive-panel" class="panel" hidden>
<div class="panel-heading"><nav id="drive-crumbs" aria-label="Folder path"></nav><div><button id="details-toggle" class="btn btn-quiet" aria-label="Show item details" aria-expanded="false" aria-controls="item-details">ⓘ</button> <button id="drive-layout" class="btn btn-quiet" aria-pressed="false">List view</button></div></div>
<div id="selection-toolbar" class="selection-toolbar" hidden><button id="selection-clear" class="btn btn-quiet" aria-label="Clear selection">×</button><strong id="selection-label">1 selected</strong><div id="selection-actions"></div></div><form id="drive-filter" class="filter-bar"><input id="drive-search" class="form-control" maxlength="200" placeholder="Search files by name" aria-label="Search files by name"><select id="drive-sort" class="form-select" aria-label="Sort files"><option value="updated">Last modified</option><option value="name">Name</option></select><button class="btn btn-quiet">Search</button></form>
<div id="drive-drop" tabindex="0" aria-label="Drop files here or use Upload document"><p>Drop files here to upload · Files stay private until security checks pass</p><div id="drive-items" class="drive-grid"></div></div>
<div class="table-footer"><span id="drive-count" role="status"></span><div><button id="drive-prev" class="btn btn-quiet">Previous</button><button id="drive-next" class="btn btn-quiet">Next</button></div></div>
</section>
<aside id="item-details" class="item-details panel" aria-label="Item details" hidden><header><h2 id="inspector-title">Details</h2><button id="details-close" class="btn btn-quiet" aria-label="Close details">×</button></header><div id="inspector-tabs"><ul><li><a href="#inspector-details">Details</a></li><li><a href="#inspector-activity">Activity</a></li></ul><div id="inspector-details"><div class="inspector-empty"><span aria-hidden="true">▤</span><p>Select an item to see its details</p></div></div><div id="inspector-activity"><p>Select an item to see its activity.</p></div></div></aside><footer class="workspace-footer"><span>School Documents</span><span>Private files · Preserved history</span></footer></main></div></div>
<div id="upload-dialog" title="Upload document" hidden><form id="upload-form"><div id="upload-tabs"><ul><li><a href="#upload-record">Record details</a></li><li><a href="#upload-file">File & expiry</a></li></ul><div id="upload-record"><p class="form-instruction">Give the document a clear name and link it to the correct school record.</p><div class="row g-3"><div class="col-12"><label for="title" class="form-label">Document title</label><input id="title" name="title" class="form-control" required maxlength="200"></div><div class="col-md-6"><label for="subject" class="form-label">{{ $personal ? 'Your name' : 'Person / record owner' }}</label><input id="subject" name="subject" value="{{ $personal ? auth()->user()->name : '' }}" class="form-control" required maxlength="200"></div><div class="col-md-6"><label for="reference" class="form-label">{{ $personal ? 'Document reference' : 'Business reference' }}</label><input id="reference" name="reference" class="form-control" placeholder="{{ $personal ? 'e.g. STUDENT-2026' : 'e.g. APP-2026-0142' }}" required maxlength="200"></div><div class="col-md-6" @if($personal) hidden @endif><label for="source" class="form-label">Source system</label><select id="source" name="source" class="form-select">@foreach(app(\App\Services\DocumentService::class)->sources(auth()->user()) as $s)<option>{{ $s }}</option>@endforeach</select></div><div class="col-md-6"><label for="category" class="form-label">Document category</label><select id="category" name="category" class="form-select">@foreach(($personal ? array_diff(config('dms.categories'), ['Payslip','Employment contract']) : config('dms.categories')) as $s)<option>{{ $s }}</option>@endforeach</select></div><div class="col-12"><label for="classification" class="form-label">Classification</label><select id="classification" name="classification" class="form-select"><option>Confidential</option><option>Restricted</option><option>Internal</option></select></div></div></div><div id="upload-file"><p class="form-instruction">Choose a file, then add an expiry date only if the document needs one.</p><label class="form-label" for="file">Select file</label><input type="file" id="file" name="file" class="form-control" accept=".pdf,.png,.jpg,.jpeg,.txt" required><p class="text-secondary small mt-2">PDF, PNG, JPG or TXT · Maximum 10 MB</p><label for="expires_at" class="form-label mt-3">Expiry date (optional)</label><input id="expires_at" name="expires_at" class="form-control" placeholder="YYYY-MM-DD" autocomplete="off"><div class="alert alert-warning mt-4">Security checks must pass before this file can be used.</div></div></div><div id="upload-error" class="alert alert-danger mt-3" role="alert" hidden></div><div class="dialog-actions"><button type="button" id="upload-cancel" class="btn btn-quiet">Cancel</button><button type="submit" id="upload-submit" class="btn btn-green">Upload document</button></div></form></div>
<div id="detail-dialog" title="Document details" hidden><div id="detail-content"></div></div>
<div id="history-dialog" title="Business record history" hidden><div id="history-detail"></div></div>
<div id="drive-dialog" title="File action" hidden><form id="drive-action-form"><div id="drive-action-fields"></div><div class="dialog-actions"><button class="btn btn-green">Save</button></div><p id="drive-action-error" class="text-danger" role="alert"></p></form></div>
<div id="preview-dialog" title="File preview" hidden><pre id="preview-text" class="history-payload" hidden></pre><img id="preview-image" alt="Private document preview" style="max-width:100%;max-height:55vh" hidden><iframe id="file-preview" title="Private file preview" sandbox style="width:100%;height:55vh;border:0" hidden></iframe><p id="preview-note" role="status"></p></div>
<div id="shared-detail-dialog" title="Shared document" hidden><h2 id="shared-title"></h2><p id="shared-access"></p><a id="shared-download" class="btn btn-green">Download shared version</a><h3 class="mt-4">Comments</h3><div id="shared-comments"></div><form id="shared-comment-form"><label for="shared-comment" class="form-label">Add a comment</label><textarea id="shared-comment" name="body" class="form-control" required maxlength="2000"></textarea><button class="btn btn-green mt-2">Post comment</button></form><form id="shared-rename-form" class="mt-4"><label for="shared-name" class="form-label">Rename document</label><input id="shared-name" class="form-control" required maxlength="200"><button class="btn btn-quiet mt-2">Save name</button></form><form id="shared-version-form" class="mt-4"><label for="shared-file" class="form-label">Upload a new version</label><input id="shared-file" type="file" class="form-control" accept=".pdf,.png,.jpg,.jpeg,.txt" required><button class="btn btn-quiet mt-2">Upload version</button><p class="small mt-2">New versions need security checks. This share keeps its original version.</p></form><p id="shared-error" class="text-danger mt-3" role="alert"></p></div>
@endsection
@section('scripts')<script src="/assets/app.js?v={{ filemtime(public_path('assets/app.js')) }}"></script><script src="/assets/drive.js?v={{ filemtime(public_path('assets/drive.js')) }}"></script><script src="/assets/folder-upload.js?v={{ filemtime(public_path('assets/folder-upload.js')) }}"></script><script src="/assets/item-details.js?v={{ filemtime(public_path('assets/item-details.js')) }}"></script><script src="/assets/dialog-scroll.js"></script>@endsection
