const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const handlers=new Map(),values=new Map(),folders=[],docs=new Map();let submit,uploads=0,failMove=true;
const picker={webkitdirectory:true,files:[],click(){}},form={addEventListener(type,fn){submit=fn;}};
function $(selector){if(typeof selector==='function'){selector();return;}if(selector===picker)selector='#folder-upload-picker';const object={0:selector==='#folder-upload-picker'?picker:form,on(event,fn){handlers.set(selector+':'+event,fn);return this;},prop(){return this;},attr(){return this;},text(value){if(value!==undefined)values.set(selector,value);return this;},val(value){if(value!==undefined)values.set(selector,value);return values.get(selector)||'';},is(){return true;},last(){return this;},data(){return null;},trigger(){return this;},dialog(){return this;},closest(){return {length:0};}};return object;}
$.getJSON=async url=>url==='/workspace/folders'?folders:{document:docs.get(url.split('/').at(-1))};
$.post=async(url,data)=>{if(url==='/workspace/folders'){const f={id:'folder-'+folders.length,name:data.name,source:data.source,parent_id:data.parent_id};folders.push(f);return f;}if(failMove){failMove=false;throw {responseJSON:{message:'Temporary move failure'}};}docs.get(url.split('/')[3]).folder_id=data.folder_id;return {ok:true};};
$.ajax=async opts=>{uploads++;const id='doc-'+uploads;docs.set(id,{folder_id:null,revision:1});assert.equal(opts.data.get('title'),opts.data.get('file').name);return {document_id:id};};
class Data extends Map{constructor(source){super();if(source){this.set('source','Enrollment');this.set('subject','Student');}}}
vm.runInNewContext(fs.readFileSync((process.argv[2]||require('node:path').resolve(__dirname,'../../public/assets/folder-upload.js')),'utf8'),{$,document:{},FormData:Data,crypto:require('node:crypto').webcrypto,console});
picker.files=[{name:'one.txt',size:12,webkitRelativePath:'Records/one.txt'},{name:'two.txt',size:12,webkitRelativePath:'Records/Term/two.txt'}];
(async()=>{handlers.get('#folder-upload-picker:change')();await submit({preventDefault(){},stopImmediatePropagation(){}});assert.equal(uploads,1);assert.match(values.get('#upload-error'),/Retry/);await submit({preventDefault(){},stopImmediatePropagation(){}});assert.equal(uploads,2,'completed upload is reused when moving is retried');assert.equal(folders.length,2,'folder structure is reused');assert.equal(docs.get('doc-1').folder_id,'folder-0');assert.equal(docs.get('doc-2').folder_id,'folder-1');console.log('Folder batch retry and structure checks passed.');})().catch(e=>{console.error(e);process.exitCode=1;});